# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a9db043ff16f96a0e01ed4af87ae8fe0e34f2b107f6e79149d87a36fa415643f92874c3a60dba58150f233032531462b4be9350ea91a17dee1103adf4f03b5f
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
test:
  secret_key_base: 1113479be56a1f53671dd3bd1cfb467feeacece2b37c121c11e7c39b883779197d7dc012a1e86f7e63ea76836bb9bdb184bbc277ad688da20dd88532734d2542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
